# configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-config
data:
  NODE_ENV: "production"
  REACT_APP_API_URL: "http://mern-backend:5000"
  MONGODB_URI: "mongodb://mern-mongodb:27017/mernapp"
