# secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: <base64-encoded-username>
  MONGO_INITDB_ROOT_PASSWORD: <base64-encoded-password>
